#cloud-config
users:
  - default
  - name: dev
    groups: sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    home: /home/dev
    shell: /bin/bash

runcmd:
  - mkdir -p /home/dev/.oh-my-zsh
  - sudo apt-get update
  - curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
  - sudo apt-get install nodejs
  - sudo apt-get install -y git zsh fonts-powerline
  - git clone --depth=1 https://github.com/romkatv/powerlevel10k.git /home/dev/powerlevel10k
  - echo 'source /home/dev/powerlevel10k/powerlevel10k.zsh-theme' >>/home/dev/.zshrc
  - echo 'cd /home/dev/codebase' >>/home/dev/.zshrc
  - cd /home/dev
  - wget https://code-server.dev/install.sh
  - sudo sh install.sh
  - git config --global --add safe.directory /home/dev/codebase
  - sudo chown -R dev /home/dev/
  - code-server --bind-addr 0.0.0.0:3001 --auth none /home/dev/codebase
